language: elixir

elixir: 1.7.0
otp_release: 20.0

env:
  - MIX_ENV=test

sudo: false
addons:
  postgresql: 9.6

before_script: mix deps.get --only test

script: mix coveralls.travis

notifications:
  email:
    on_success: never
