language: elixir

elixir: 1.6.6
otp_release: 21.0

sudo: false
addons:
  postgresql: 9.6

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_script:
  - mix deps.get --only test

script:
  - mix compile
  - mix test
